services:
  - type: web
    name: sow-backend-service
    env: python
    plan: free
    rootDir: sow-backend
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn src.app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.11.0"